# Site settings
title: evangellion.github.io
email: i.kacper@gmail.com
description:  my external memory
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evangellion.github.io/" # the base hostname & protocol for your site
twitter_username: evangellionlive
github_username:  evangellion

# Build settings
markdown: kramdown

collections:
  presentations:
    output: true
    permalink: /prezentacjie/:path/
  blogs:
    output: true
    layout: post
    permalink: /blogi/:path/
